DELETE http://localhost:3001/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdGVubEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzc1MTk5MTM2fQ.Vi1D_ZsSzl2dgsi-yvYruyq92A9JS4RKeVeTWN_pdZ8