POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdGVubEBnbWFpbC5jb20iLCJpZCI6ODIsImlhdCI6MTc3NTIwNDgwNX0._oEuCGtnGklGt0fB_6IxYehOnmW3jCoFFJlg_sVo5Yc

{
    "title": "Blog with Second Token",
    "author": "Token2",
    "url": "https://example.com/token2"
}