POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdGVudkBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzc1MDI2NTY3fQ.26_Q-ddSfw_bPxdi-ysb1rD06iv2-2EJaTL74gARI18

{
    "author": "dotenl.com",
    "url": "https://=",
    "title": "REACT",
    "likes": 20
}